### PR TITLE
consist config values with one load point

### LINKED ISSUE #14: Config is read twice
Because of 

`var cfg       = config.loadConfig();`

in postifx doc loadConfig gets called twice, the first time from /etc and the second time from current folder.

How do you feel about using node-config module instead?

### PR DESCRIPTION
**Pull request by msimerson**
* remove need to call config.loadConfig
* add a this.postdoc to logship
* postdoc gets config when loaded by logship
    * switch postfix-doc from exports to object w/prototypes

fixes #14

### CODE REVIEW

**Comment by jaredj** [comment]
looks like this needs rebased?

**Comment by urosgruber** [comment]
@msimerson It's better. Just a question about try/catch. So In case local file is there, it uses this file and never touches the one in /etc for example. But If I remove local file It uses correct config but errors out that can't read local file. What if instead of logger.error inside catch to output something like `logger.error("No configuration found");` at the end of for loop.

**Comment by msimerson** [comment]
> So In case local file is there, it uses this file and never touches the one in /etc for example.

Ahhh, I see your problem. `server.js` was passing in the value `./` for the etcDir, which had the effect of preferring the local config file over one installed in /etc. I have removed that, and added a -c option, so one can specify a preferred config dir.

**Comment by urosgruber** [comment]
I works perfectly now. I need to run some other test but it's no in scope of this change.

**Pull request merged**
